In [3]:
import pandas as pd

In [15]:
df = pd.read_csv('DimCustomer.csv')

In [16]:
df.head()

,Unnamed: 0,CustomerKey,GeographyKey,FirstName,LastName,BirthDate,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,Education,Occupation,HouseOwnerFlag,NumberCarsOwned
0,0,1,680,Jon,Yang,1966-04-08,M,M,90000.0,2.0,0.0,Bachelors,Professional,1.0,0.0
1,1,2,692,Eugene,Huang,1965-05-14,S,M,60000.0,3.0,3.0,Bachelors,Professional,0.0,1.0
2,2,3,493,Ruben,Torres,1965-08-12,M,M,60000.0,3.0,3.0,Bachelors,Professional,1.0,1.0
3,3,4,519,Christy,Zhu,1968-02-15,S,F,70000.0,0.0,0.0,Bachelors,Professional,0.0,1.0
4,4,5,706,Elizabeth,Johnson,1968-08-08,S,F,80000.0,5.0,5.0,Bachelors,Professional,1.0,4.0

In [17]:
df.tail()

,Unnamed: 0,CustomerKey,GeographyKey,FirstName,LastName,BirthDate,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,Education,Occupation,HouseOwnerFlag,NumberCarsOwned
18864,18864,19141,731,Not Provided,Not Provided,1970-02-01,M,F,10000000.0,2.0,1.0,Bachelors,Management,1.0,0.0
18865,18865,19142,732,Not Provided,Not Provided,1989-02-16,S,F,10000000.0,1.0,1.0,Bachelors,Manual,1.0,0.0
18866,18866,19143,733,Not Provided,Not Provided,1980-07-23,M,M,10000000.0,3.0,1.0,Graduate Degree,Management,1.0,2.0
18867,18867,19144,734,Not Provided,Not Provided,1982-08-28,M,M,10000000.0,1.0,0.0,Partial College,Management,0.0,1.0
18868,18868,19145,735,Not Provided,Not Provided,1967-06-19,S,M,10000000.0,5.0,5.0,Partial High School,Clerical,1.0,2.0

In [18]:
df.shape

(18869, 15)

In [20]:
df.info

<bound method DataFrame.info of        Unnamed: 0  CustomerKey  GeographyKey     FirstName      LastName  \
0               0            1           680           Jon          Yang
1               1            2           692        Eugene         Huang
2               2            3           493         Ruben        Torres
3               3            4           519       Christy           Zhu
4               4            5           706     Elizabeth       Johnson
...           ...          ...           ...           ...           ...
18864       18864        19141           731  Not Provided  Not Provided
18865       18865        19142           732  Not Provided  Not Provided
18866       18866        19143           733  Not Provided  Not Provided
18867       18867        19144           734  Not Provided  Not Provided
18868       18868        19145           735  Not Provided  Not Provided

        BirthDate MaritalStatus Gender  YearlyIncome  TotalChildren  \
0      1966-04-08             M      M       90000.0            2.0
1      1965-05-14             S      M       60000.0            3.0
2      1965-08-12             M      M       60000.0            3.0
3      1968-02-15             S      F       70000.0            0.0
4      1968-08-08             S      F       80000.0            5.0
...           ...           ...    ...           ...            ...
18864  1970-02-01             M      F    10000000.0            2.0
18865  1989-02-16             S      F    10000000.0            1.0
18866  1980-07-23             M      M    10000000.0            3.0
18867  1982-08-28             M      M    10000000.0            1.0
18868  1967-06-19             S      M    10000000.0            5.0

       NumberChildrenAtHome            Education    Occupation  \
0                       0.0            Bachelors  Professional
1                       3.0            Bachelors  Professional
2                       3.0            Bachelors  Professional
3                       0.0            Bachelors  Professional
4                       5.0            Bachelors  Professional
...                     ...                  ...           ...
18864                   1.0            Bachelors    Management
18865                   1.0            Bachelors        Manual
18866                   1.0      Graduate Degree    Management
18867                   0.0      Partial College    Management
18868                   5.0  Partial High School      Clerical

       HouseOwnerFlag  NumberCarsOwned
0                 1.0              0.0
1                 0.0              1.0
2                 1.0              1.0
3                 0.0              1.0
4                 1.0              4.0
...               ...              ...
18864             1.0              0.0
18865             1.0              0.0
18866             1.0              2.0
18867             0.0              1.0
18868             1.0              2.0

[18869 rows x 15 columns]>

In [21]:
df.describe

<bound method NDFrame.describe of        Unnamed: 0  CustomerKey  GeographyKey     FirstName      LastName  \
0               0            1           680           Jon          Yang
1               1            2           692        Eugene         Huang
2               2            3           493         Ruben        Torres
3               3            4           519       Christy           Zhu
4               4            5           706     Elizabeth       Johnson
...           ...          ...           ...           ...           ...
18864       18864        19141           731  Not Provided  Not Provided
18865       18865        19142           732  Not Provided  Not Provided
18866       18866        19143           733  Not Provided  Not Provided
18867       18867        19144           734  Not Provided  Not Provided
18868       18868        19145           735  Not Provided  Not Provided

        BirthDate MaritalStatus Gender  YearlyIncome  TotalChildren  \
0      1966-04-08             M      M       90000.0            2.0
1      1965-05-14             S      M       60000.0            3.0
2      1965-08-12             M      M       60000.0            3.0
3      1968-02-15             S      F       70000.0            0.0
4      1968-08-08             S      F       80000.0            5.0
...           ...           ...    ...           ...            ...
18864  1970-02-01             M      F    10000000.0            2.0
18865  1989-02-16             S      F    10000000.0            1.0
18866  1980-07-23             M      M    10000000.0            3.0
18867  1982-08-28             M      M    10000000.0            1.0
18868  1967-06-19             S      M    10000000.0            5.0

       NumberChildrenAtHome            Education    Occupation  \
0                       0.0            Bachelors  Professional
1                       3.0            Bachelors  Professional
2                       3.0            Bachelors  Professional
3                       0.0            Bachelors  Professional
4                       5.0            Bachelors  Professional
...                     ...                  ...           ...
18864                   1.0            Bachelors    Management
18865                   1.0            Bachelors        Manual
18866                   1.0      Graduate Degree    Management
18867                   0.0      Partial College    Management
18868                   5.0  Partial High School      Clerical

       HouseOwnerFlag  NumberCarsOwned
0                 1.0              0.0
1                 0.0              1.0
2                 1.0              1.0
3                 0.0              1.0
4                 1.0              4.0
...               ...              ...
18864             1.0              0.0
18865             1.0              0.0
18866             1.0              2.0
18867             0.0              1.0
18868             1.0              2.0

[18869 rows x 15 columns]>

In [22]:
novo_df = df[["LastName", "YearlyIncome", "Education"]]

In [24]:
novo_df.head(10)

  LastName  YearlyIncome  Education
0     Yang       90000.0  Bachelors
1    Huang       60000.0  Bachelors
2   Torres       60000.0  Bachelors
3      Zhu       70000.0  Bachelors
4  Johnson       80000.0  Bachelors
5     Ruiz       70000.0  Bachelors
6  Alvarez       70000.0  Bachelors
7    Mehta       60000.0  Bachelors
8  Verhoff       60000.0  Bachelors
9  Carlson       70000.0  Bachelors

In [27]:
filtro_salario = df[df["YearlyIncome"] > 150000]

In [28]:
filtro_salario.head(10)

,Unnamed: 0,CustomerKey,GeographyKey,FirstName,LastName,BirthDate,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,Education,Occupation,HouseOwnerFlag,NumberCarsOwned
79,79,80,632,Donald,Gonzalez,1959-03-11,S,M,160000.0,0.0,0.0,Graduate Degree,Management,1.0,2.0
80,80,81,531,Damien,Chander,1959-07-17,M,M,170000.0,0.0,0.0,Graduate Degree,Management,1.0,2.0
180,180,181,610,April,Anand,1943-01-02,M,F,160000.0,1.0,3.0,Bachelors,Management,1.0,4.0
181,181,182,653,Devin,Martin,1943-08-08,M,M,170000.0,2.0,3.0,Graduate Degree,Management,1.0,2.0
240,240,241,704,Anne,Hernandez,1958-12-11,M,F,160000.0,2.0,3.0,Partial College,Professional,1.0,4.0
244,244,245,541,Alexis,Coleman,1957-11-26,S,F,170000.0,2.0,3.0,Bachelors,Management,0.0,3.0
250,250,251,574,Shannon,Liu,1955-03-12,M,F,170000.0,3.0,4.0,High School,Professional,1.0,2.0
286,286,287,560,Hunter,Griffin,1962-03-03,M,M,170000.0,0.0,0.0,Graduate Degree,Management,1.0,4.0
422,422,423,651,Dustin,Deng,1946-09-01,M,M,170000.0,4.0,4.0,Bachelors,Management,1.0,3.0
434,434,435,705,Andre,Lopez,1951-05-06,M,M,170000.0,5.0,5.0,Partial College,Professional,1.0,4.0

In [29]:
media_salarial = df["YearlyIncome"].mean()

In [30]:
media_salarial

np.float64(260174.8900312682)