In [ ]:
#pip install pandas 
#conectar o google drive
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

Mounted at /content/drive

In [ ]:
#acessar diretorio do google drive
cd /content/drive/MyDrive/projetos

/content/drive/MyDrive/projetos

In [41]:
df = pd.read_csv('DimCustomer.csv')

In [9]:
df.head(2)

,Unnamed: 0,CustomerKey,GeographyKey,FirstName,LastName,BirthDate,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,Education,Occupation,HouseOwnerFlag,NumberCarsOwned
0,0,1,680,Jon,Yang,1966-04-08,M,M,90000.0,2.0,0.0,Bachelors,Professional,1.0,0.0
1,1,2,692,Eugene,Huang,1965-05-14,S,M,60000.0,3.0,3.0,Bachelors,Professional,0.0,1.0

In [10]:
df.shape

(18869, 15)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18869 entries, 0 to 18868
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            18869 non-null  int64
 1   CustomerKey           18869 non-null  int64
 2   GeographyKey          18869 non-null  int64
 3   FirstName             18869 non-null  object
 4   LastName              18869 non-null  object
 5   BirthDate             18869 non-null  object
 6   MaritalStatus         18869 non-null  object
 7   Gender                18869 non-null  object
 8   YearlyIncome          18869 non-null  float64
 9   TotalChildren         18869 non-null  float64
 10  NumberChildrenAtHome  18869 non-null  float64
 11  Education             18869 non-null  object
 12  Occupation            18869 non-null  object
 13  HouseOwnerFlag        18869 non-null  float64
 14  NumberCarsOwned       18869 non-null  float64
dtypes: float64(5), int64(3), object(7)
memory usage: 2.2+ MB

In [13]:
df.tail()

,Unnamed: 0,CustomerKey,GeographyKey,FirstName,LastName,BirthDate,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,Education,Occupation,HouseOwnerFlag,NumberCarsOwned
18864,18864,19141,731,Not Provided,Not Provided,1970-02-01,M,F,10000000.0,2.0,1.0,Bachelors,Management,1.0,0.0
18865,18865,19142,732,Not Provided,Not Provided,1989-02-16,S,F,10000000.0,1.0,1.0,Bachelors,Manual,1.0,0.0
18866,18866,19143,733,Not Provided,Not Provided,1980-07-23,M,M,10000000.0,3.0,1.0,Graduate Degree,Management,1.0,2.0
18867,18867,19144,734,Not Provided,Not Provided,1982-08-28,M,M,10000000.0,1.0,0.0,Partial College,Management,0.0,1.0
18868,18868,19145,735,Not Provided,Not Provided,1967-06-19,S,M,10000000.0,5.0,5.0,Partial High School,Clerical,1.0,2.0

In [ ]:
df["novacoluna"] = df['TotalChildren'] + df['NumberChildrenAtHome']

In [15]:
df.head()

,Unnamed: 0,CustomerKey,GeographyKey,FirstName,LastName,BirthDate,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,Education,Occupation,HouseOwnerFlag,NumberCarsOwned,novacoluna
0,0,1,680,Jon,Yang,1966-04-08,M,M,90000.0,2.0,0.0,Bachelors,Professional,1.0,0.0,2.0
1,1,2,692,Eugene,Huang,1965-05-14,S,M,60000.0,3.0,3.0,Bachelors,Professional,0.0,1.0,6.0
2,2,3,493,Ruben,Torres,1965-08-12,M,M,60000.0,3.0,3.0,Bachelors,Professional,1.0,1.0,6.0
3,3,4,519,Christy,Zhu,1968-02-15,S,F,70000.0,0.0,0.0,Bachelors,Professional,0.0,1.0,0.0
4,4,5,706,Elizabeth,Johnson,1968-08-08,S,F,80000.0,5.0,5.0,Bachelors,Professional,1.0,4.0,10.0

In [20]:
df.iloc[5:10, 0:8]

,Unnamed: 0,CustomerKey,GeographyKey,FirstName,LastName,BirthDate,MaritalStatus,Gender
5,5,6,478,Julio,Ruiz,1965-08-05,S,M
6,6,7,509,Janet,Alvarez,1965-12-06,S,F
7,7,8,568,Marco,Mehta,1964-05-09,M,M
8,8,9,425,Rob,Verhoff,1964-07-07,S,F
9,9,10,492,Shannon,Carlson,1964-04-01,S,M

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18869 entries, 0 to 18868
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            18869 non-null  int64
 1   CustomerKey           18869 non-null  int64
 2   GeographyKey          18869 non-null  int64
 3   FirstName             18869 non-null  object
 4   LastName              18869 non-null  object
 5   BirthDate             18869 non-null  object
 6   MaritalStatus         18869 non-null  object
 7   Gender                18869 non-null  object
 8   YearlyIncome          18869 non-null  float64
 9   TotalChildren         18869 non-null  float64
 10  NumberChildrenAtHome  18869 non-null  float64
 11  Education             18869 non-null  object
 12  Occupation            18869 non-null  object
 13  HouseOwnerFlag        18869 non-null  float64
 14  NumberCarsOwned       18869 non-null  float64
 15  novacoluna            18869 non-null  float64
dtypes: float64(6), int64(3), object(7)
memory usage: 2.3+ MB

In [ ]:
novo_df = df[["LastName", "YearlyIncome", "Education"]]

In [25]:
novo_df.head()

  LastName  YearlyIncome  Education
0     Yang       90000.0  Bachelors
1    Huang       60000.0  Bachelors
2   Torres       60000.0  Bachelors
3      Zhu       70000.0  Bachelors
4  Johnson       80000.0  Bachelors

In [23]:
df

,Unnamed: 0,CustomerKey,GeographyKey,FirstName,LastName,BirthDate,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,Education,Occupation,HouseOwnerFlag,NumberCarsOwned,novacoluna
0,0,1,680,Jon,Yang,1966-04-08,M,M,90000.0,2.0,0.0,Bachelors,Professional,1.0,0.0,2.0
1,1,2,692,Eugene,Huang,1965-05-14,S,M,60000.0,3.0,3.0,Bachelors,Professional,0.0,1.0,6.0
2,2,3,493,Ruben,Torres,1965-08-12,M,M,60000.0,3.0,3.0,Bachelors,Professional,1.0,1.0,6.0
3,3,4,519,Christy,Zhu,1968-02-15,S,F,70000.0,0.0,0.0,Bachelors,Professional,0.0,1.0,0.0
4,4,5,706,Elizabeth,Johnson,1968-08-08,S,F,80000.0,5.0,5.0,Bachelors,Professional,1.0,4.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18864,18864,19141,731,Not Provided,Not Provided,1970-02-01,M,F,10000000.0,2.0,1.0,Bachelors,Management,1.0,0.0,3.0
18865,18865,19142,732,Not Provided,Not Provided,1989-02-16,S,F,10000000.0,1.0,1.0,Bachelors,Manual,1.0,0.0,2.0
18866,18866,19143,733,Not Provided,Not Provided,1980-07-23,M,M,10000000.0,3.0,1.0,Graduate Degree,Management,1.0,2.0,4.0
18867,18867,19144,734,Not Provided,Not Provided,1982-08-28,M,M,10000000.0,1.0,0.0,Partial College,Management,0.0,1.0,1.0
18868,18868,19145,735,Not Provided,Not Provided,1967-06-19,S,M,10000000.0,5.0,5.0,Partial High School,Clerical,1.0,2.0,10.0

In [31]:
df[df["MaritalStatus"] == "S"]

,Unnamed: 0,CustomerKey,GeographyKey,FirstName,LastName,BirthDate,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,Education,Occupation,HouseOwnerFlag,NumberCarsOwned,novacoluna
1,1,2,692,Eugene,Huang,1965-05-14,S,M,60000.0,3.0,3.0,Bachelors,Professional,0.0,1.0,6.0
3,3,4,519,Christy,Zhu,1968-02-15,S,F,70000.0,0.0,0.0,Bachelors,Professional,0.0,1.0,0.0
4,4,5,706,Elizabeth,Johnson,1968-08-08,S,F,80000.0,5.0,5.0,Bachelors,Professional,1.0,4.0,10.0
5,5,6,478,Julio,Ruiz,1965-08-05,S,M,70000.0,0.0,0.0,Bachelors,Professional,1.0,1.0,0.0
6,6,7,509,Janet,Alvarez,1965-12-06,S,F,70000.0,0.0,0.0,Bachelors,Professional,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18857,18857,19134,724,Not Provided,Not Provided,1967-11-03,S,M,10000000.0,2.0,1.0,Bachelors,Manual,0.0,4.0,3.0
18858,18858,19135,725,Not Provided,Not Provided,1960-05-26,S,M,10000000.0,2.0,0.0,Partial College,Clerical,0.0,4.0,2.0
18860,18860,19137,727,Not Provided,Not Provided,1974-09-06,S,M,10000000.0,1.0,0.0,Partial College,Clerical,0.0,2.0,1.0
18865,18865,19142,732,Not Provided,Not Provided,1989-02-16,S,F,10000000.0,1.0,1.0,Bachelors,Manual,1.0,0.0,2.0
18868,18868,19145,735,Not Provided,Not Provided,1967-06-19,S,M,10000000.0,5.0,5.0,Partial High School,Clerical,1.0,2.0,10.0

In [34]:
df.nlargest(5, "TotalChildren")

,Unnamed: 0,CustomerKey,GeographyKey,FirstName,LastName,BirthDate,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,Education,Occupation,HouseOwnerFlag,NumberCarsOwned,novacoluna
4,4,5,706,Elizabeth,Johnson,1968-08-08,S,F,80000.0,5.0,5.0,Bachelors,Professional,1.0,4.0,10.0
102,102,103,558,Julia,Nelson,1965-04-21,S,F,80000.0,5.0,5.0,Bachelors,Professional,1.0,4.0,10.0
113,113,114,531,Micheal,Blanco,1962-02-21,M,M,70000.0,5.0,4.0,Bachelors,Professional,1.0,2.0,9.0
114,114,115,679,Leslie,Moreno,1962-05-28,S,F,70000.0,5.0,4.0,Partial College,Skilled Manual,1.0,2.0,9.0
115,115,116,554,Alvin,Cai,1962-02-12,M,M,70000.0,5.0,4.0,Partial College,Skilled Manual,1.0,2.0,9.0

In [36]:
df.nsmallest(5, "YearlyIncome")

,Unnamed: 0,CustomerKey,GeographyKey,FirstName,LastName,BirthDate,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,Education,Occupation,HouseOwnerFlag,NumberCarsOwned,novacoluna
25,25,26,637,Alejandro,Beck,1945-12-23,M,M,10000.0,2.0,1.0,Partial High School,Clerical,1.0,2.0,3.0
30,30,31,613,Bethany,Yuan,1947-02-22,M,F,10000.0,2.0,1.0,Partial High School,Clerical,1.0,2.0,3.0
35,35,36,471,Wendy,Dominguez,1948-02-24,M,F,10000.0,2.0,1.0,Partial High School,Clerical,1.0,2.0,3.0
38,38,39,648,Diana,Hernandez,1948-03-23,M,F,10000.0,2.0,1.0,Partial High School,Clerical,1.0,2.0,3.0
126,126,127,519,Shaun,Carson,1949-04-07,M,M,10000.0,2.0,1.0,High School,Skilled Manual,0.0,2.0,3.0

In [45]:
media_salarial = df["YearlyIncome"].mean()

print (f"A Média anual salarial é: R${round (media_salarial, 2)}")

A Média anual salarial é: R$260174.89

In [47]:
soma_salario = df["YearlyIncome"].sum()

In [48]:
soma_salario

np.float64(4909240000.0)

In [51]:
df["YearlyIncome"].std()

1406070.9443231185

In [52]:
df.describe()

,Unnamed: 0,CustomerKey,GeographyKey,YearlyIncome,TotalChildren,NumberChildrenAtHome,HouseOwnerFlag,NumberCarsOwned
count,18869.00000,18869.000000,18869.000000,1.886900e+04,18869.000000,18869.000000,18869.000000,18869.000000
mean,9434.00000,9440.631459,574.910435,2.601749e+05,1.856219,1.034077,0.673274,1.513753
std,5447.15545,5456.841811,84.163867,1.406071e+06,1.615868,1.541922,0.469029,1.146417
min,0.00000,1.000000,423.000000,1.000000e+04,0.000000,0.000000,0.000000,0.000000
25%,4717.00000,4718.000000,506.000000,3.000000e+04,0.000000,0.000000,0.000000,1.000000
50%,9434.00000,9435.000000,568.000000,6.000000e+04,2.000000,0.000000,1.000000,2.000000
75%,14151.00000,14152.000000,645.000000,8.000000e+04,3.000000,2.000000,1.000000,2.000000
max,18868.00000,19145.000000,952.000000,1.000000e+07,5.000000,5.000000,1.000000,4.000000

In [53]:
media_feminina = df[df['Gender'] == 'F']['YearlyIncome'].mean().round(2)
media_masculina = df[df['Gender'] == 'M']['YearlyIncome'].mean().round(2)

In [54]:
media_feminina

np.float64(281887.84)

In [55]:
media_masculina

np.float64(238874.54)

In [56]:
df.head()

,Unnamed: 0,CustomerKey,GeographyKey,FirstName,LastName,BirthDate,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,Education,Occupation,HouseOwnerFlag,NumberCarsOwned
0,0,1,680,Jon,Yang,1966-04-08,M,M,90000.0,2.0,0.0,Bachelors,Professional,1.0,0.0
1,1,2,692,Eugene,Huang,1965-05-14,S,M,60000.0,3.0,3.0,Bachelors,Professional,0.0,1.0
2,2,3,493,Ruben,Torres,1965-08-12,M,M,60000.0,3.0,3.0,Bachelors,Professional,1.0,1.0
3,3,4,519,Christy,Zhu,1968-02-15,S,F,70000.0,0.0,0.0,Bachelors,Professional,0.0,1.0
4,4,5,706,Elizabeth,Johnson,1968-08-08,S,F,80000.0,5.0,5.0,Bachelors,Professional,1.0,4.0

In [61]:
df["MaritalStatus"].value_counts()

MaritalStatus
M    10188
S     8681
Name: count, dtype: int64

In [58]:
df.shape

(18869, 15)

In [64]:
df.describe()

,Unnamed: 0,CustomerKey,GeographyKey,YearlyIncome,TotalChildren,NumberChildrenAtHome,HouseOwnerFlag,NumberCarsOwned
count,18869.00000,18869.000000,18869.000000,1.886900e+04,18869.000000,18869.000000,18869.000000,18869.000000
mean,9434.00000,9440.631459,574.910435,2.601749e+05,1.856219,1.034077,0.673274,1.513753
std,5447.15545,5456.841811,84.163867,1.406071e+06,1.615868,1.541922,0.469029,1.146417
min,0.00000,1.000000,423.000000,1.000000e+04,0.000000,0.000000,0.000000,0.000000
25%,4717.00000,4718.000000,506.000000,3.000000e+04,0.000000,0.000000,0.000000,1.000000
50%,9434.00000,9435.000000,568.000000,6.000000e+04,2.000000,0.000000,1.000000,2.000000
75%,14151.00000,14152.000000,645.000000,8.000000e+04,3.000000,2.000000,1.000000,2.000000
max,18868.00000,19145.000000,952.000000,1.000000e+07,5.000000,5.000000,1.000000,4.000000

In [63]:
df["YearlyIncome"].mean().round(2)

np.float64(260174.89)